site_name: CooperHouse Developer Guide
site_author: Tim Cooper, Dane Strom, Colton Anglin
repo_url: https://github.com/cooperhouse/developer-guide/

#nav:
#    - 'Introduction': 'index.md'
 #   - 'User Guide': 'user-guide.md'
 #   - 'About': 'about.md'
